services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - database_data:/var/lib/mysql

  

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - 127.0.0.1:${PRESIDIO_ANONYMIZER_PORT}:3000

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - 127.0.0.1:${PRESIDIO_ANALYZER_PORT}:3000

volumes:
  database_data:
