export const ANALYTICS_HISTORY_DAYS = 7;
export const ANALYTICS_RECENT_ACTIVITY_LIMIT = 10;
export const ANALYTICS_ACTIVITY_LIMIT_MAX = 100;
export const ANALYTICS_DEFAULT_SUCCESS_RATE = 100;
export const ANALYTICS_PERCENTAGE_MULTIPLIER = 1000;
export const ANALYTICS_PERCENTAGE_DIVISOR = 10;

export const CONFIDENCE_RANGE_90_100 = '90-100';
export const CONFIDENCE_RANGE_80_90 = '80-90';
export const CONFIDENCE_RANGE_70_80 = '70-80';
export const CONFIDENCE_RANGE_60_70 = '60-70';
export const CONFIDENCE_RANGE_BELOW_60 = '<60';

export const CONFIDENCE_SCORE_HIGH = 0.9;
export const CONFIDENCE_SCORE_MEDIUM_HIGH = 0.8;
export const CONFIDENCE_SCORE_MEDIUM = 0.7;
export const CONFIDENCE_SCORE_LOW = 0.6;

export const CONFIDENCE_RANGE_ORDER: Record<string, number> = {
  [CONFIDENCE_RANGE_90_100]: 0,
  [CONFIDENCE_RANGE_80_90]: 1,
  [CONFIDENCE_RANGE_70_80]: 2,
  [CONFIDENCE_RANGE_60_70]: 3,
  [CONFIDENCE_RANGE_BELOW_60]: 4,
};
